### ISSUE TITLE
Push and Pop calls don't block, but rather just time out

### ISSUE THREAD

**Issue by cboggs** [joekain/BlockingQueue#6]
Hi!

I've been reading through your Learning Elixir blog and I'm really enjoying it! I wanted to play around with your blocking queue, however, and find that the public API you provide via the BlockingQueue.push and BlockingQueue.pop methods don't seem to account for the default timeout of 5s imposed by GenServer.call.

Example:
```
iex(1)> {:ok, q} = BlockingQueue.start_link(5)
{:ok, #PID<0.231.0>}
iex(2)> BlockingQueue.pop q
** (exit) exited in: GenServer.call(#PID<0.231.0>, :pop, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:564: GenServer.call/3
iex(2)> {:ok, q} = BlockingQueue.start_link(2)
{:ok, #PID<0.234.0>}
iex(3)> BlockingQueue.push q, 1
nil
iex(4)> BlockingQueue.push q, 2
nil
iex(5)> BlockingQueue.push q, 3
** (exit) exited in: GenServer.call(#PID<0.234.0>, {:push, 3}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:564: GenServer.call/3
```

I suspect I'm doing something I shouldn't, but thought I would ask if this is the expected behavior. :-)

**Comment by joekain** [comment]
Hi @cboggs,  This is definitely a problem and is something I've run into a few times.  It should probably get fixed but I haven't been able to take care of yet.

**Comment by cboggs** [comment]
Sounds good, thanks for verifying for me. :-) 

Seems like a decent learning opportunity for me, I'll see if I can come up with a reasonably good fix and submit a PR.

**Comment by cboggs** [comment]
PR #7 should address this, will close the issue.
